import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { runAllChecks, runCheck, applyFix } from './checks/index.js';
import { getTemperatureData } from './checks/temperature.js';
import { scripts, getScriptsForPlatform, detectPlatform } from './scripts.js';
import { generateFixSuggestions, searchForSolutions } from './ai-fix.js';
import { checkClawdbot, checkClawdbotDeep } from './checks/clawdbot.js';

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

// Health endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Get temperature data (lightweight, for live widget)
app.get('/api/temperature', async (req, res) => {
  try {
    const data = await getTemperatureData();
    res.json(data);
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Get all security checks
app.get('/api/checks', async (req, res) => {
  try {
    const results = await runAllChecks();
    res.json(results);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Run a specific check
app.get('/api/checks/:checkId', async (req, res) => {
  try {
    const result = await runCheck(req.params.checkId);
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Apply a fix
app.post('/api/fixes/:fixId', async (req, res) => {
  try {
    const result = await applyFix(req.params.fixId, req.body);
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get available fix scripts
app.get('/api/scripts', (req, res) => {
  const platform = req.query.platform || detectPlatform(req.headers['user-agent']);
  res.json({
    platform,
    scripts: getScriptsForPlatform(platform),
    all: scripts
  });
});

// Get specific script info
app.get('/api/scripts/:scriptId', (req, res) => {
  const script = scripts[req.params.scriptId];
  if (!script) {
    return res.status(404).json({ error: 'Script not found' });
  }
  res.json(script);
});

// Download script file
app.get('/api/scripts/:scriptId/download', (req, res) => {
  const { scriptId } = req.params;
  const platform = req.query.platform || 'linux';
  const script = scripts[scriptId];
  
  if (!script) {
    return res.status(404).json({ error: 'Script not found' });
  }
  
  const platformScript = script.platforms?.[platform];
  if (!platformScript) {
    return res.status(404).json({ error: `Script not available for ${platform}` });
  }
  
  // Generate script content based on script ID
  const content = generateScriptContent(scriptId, platform);
  const filename = platform === 'windows' ? `${scriptId}.ps1` : `${scriptId}.sh`;
  
  res.setHeader('Content-Type', 'text/plain');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send(content);
});

// Script content generator
function generateScriptContent(scriptId, platform) {
  const scriptTemplates = {
    'enable-firewall': {
      linux: `#!/bin/bash
# Enable Firewall Script
# Generated by Security Dashboard

set -e

echo "🛡️ Enabling firewall..."

# Detect and enable firewall
if command -v ufw &> /dev/null; then
    echo "Using UFW..."
    sudo ufw --force enable
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    sudo ufw allow ssh
    sudo ufw status verbose
elif command -v firewall-cmd &> /dev/null; then
    echo "Using firewalld..."
    sudo systemctl start firewalld
    sudo systemctl enable firewalld
    sudo firewall-cmd --set-default-zone=public
    sudo firewall-cmd --permanent --add-service=ssh
    sudo firewall-cmd --reload
    sudo firewall-cmd --list-all
else
    echo "Using iptables..."
    sudo iptables -P INPUT DROP
    sudo iptables -P FORWARD DROP
    sudo iptables -P OUTPUT ACCEPT
    sudo iptables -A INPUT -i lo -j ACCEPT
    sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
    sudo iptables -L -v
fi

echo "✅ Firewall enabled successfully!"
`,
      windows: `# Enable Windows Firewall
# Run as Administrator

Write-Host "🛡️ Enabling Windows Firewall..." -ForegroundColor Cyan

# Enable firewall for all profiles
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True

# Set default policies
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultOutboundAction Allow

# Enable logging
Set-NetFirewallProfile -Profile Domain,Public,Private -LogBlocked True

Write-Host "✅ Windows Firewall enabled!" -ForegroundColor Green
Get-NetFirewallProfile | Format-Table Name, Enabled, DefaultInboundAction
`
    },
    'install-updates': {
      linux: `#!/bin/bash
# Install System Updates
# Generated by Security Dashboard

set -e

echo "📦 Installing system updates..."

if command -v apt &> /dev/null; then
    sudo apt update
    sudo apt upgrade -y
    sudo apt autoremove -y
elif command -v dnf &> /dev/null; then
    sudo dnf check-update || true
    sudo dnf upgrade -y
elif command -v yum &> /dev/null; then
    sudo yum check-update || true
    sudo yum update -y
elif command -v pacman &> /dev/null; then
    sudo pacman -Syu --noconfirm
else
    echo "❌ Unknown package manager"
    exit 1
fi

echo "✅ Updates installed successfully!"
`,
      windows: `# Install Windows Updates
# Run as Administrator

Write-Host "📦 Checking for Windows Updates..." -ForegroundColor Cyan

# Install PSWindowsUpdate module if not present
if (!(Get-Module -ListAvailable -Name PSWindowsUpdate)) {
    Install-Module PSWindowsUpdate -Force -Confirm:\$false
}

Import-Module PSWindowsUpdate

# Get and install updates
Get-WindowsUpdate -AcceptAll -Install -AutoReboot

Write-Host "✅ Updates installed!" -ForegroundColor Green
`
    },
    'harden-ssh': {
      linux: `#!/bin/bash
# Harden SSH Configuration
# Generated by Security Dashboard
# ⚠️ WARNING: This disables password auth. Ensure you have SSH key access!

set -e

echo "🔐 Hardening SSH configuration..."

# Backup original config
sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.\$(date +%Y%m%d)

# Apply hardening
sudo sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sudo sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
sudo sed -i 's/#MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config
sudo sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# Restart SSH
sudo systemctl restart sshd || sudo service ssh restart

echo "✅ SSH hardened successfully!"
echo "⚠️ Password authentication is now DISABLED"
`
    }
  };
  
  const template = scriptTemplates[scriptId]?.[platform];
  if (template) return template;
  
  // Default fallback
  return platform === 'windows' 
    ? \`# Script: \${scriptId}\\n# Platform: \${platform}\\nWrite-Host "Script not yet implemented"\`
    : \`#!/bin/bash\\n# Script: \${scriptId}\\n# Platform: \${platform}\\necho "Script not yet implemented"\`;
}

// AI-powered fix suggestions
app.post('/api/ai-fix', async (req, res) => {
  try {
    const { check, platform } = req.body;
    if (!check) {
      return res.status(400).json({ error: 'Missing check data' });
    }
    
    const suggestions = await generateFixSuggestions(check, platform);
    res.json(suggestions);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Search for solutions
app.get('/api/search-fix', async (req, res) => {
  try {
    const { query, platform } = req.query;
    if (!query) {
      return res.status(400).json({ error: 'Missing query parameter' });
    }
    
    const results = await searchForSolutions(query, platform || 'linux');
    res.json(results);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Clawdbot security audit
app.get('/api/clawdbot/audit', async (req, res) => {
  try {
    const result = await checkClawdbot();
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Clawdbot deep audit
app.get('/api/clawdbot/audit/deep', async (req, res) => {
  try {
    const result = await checkClawdbotDeep();
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(PORT, () => {
  console.log(`
🛡️  ═══════════════════════════════════════════════════ 🛡️
    Security Dashboard Backend
    
    🚀 Server running on port ${PORT}
    📡 API: http://localhost:${PORT}/api
    💚 Health: http://localhost:${PORT}/health
🛡️  ═══════════════════════════════════════════════════ 🛡️
  `);
});
